#ifndef SAMI_ERR_MSGTH
#define SAMI_ERR_MSGTH 1
/*  Message table include file
 *  Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 *  from input file sami_err.msg at Sun Apr 28 14:25:43 2019
  */
static MessTabType MessFacTab_SAMI[] = {
    { 2, "FILE_PARSE", 
        "File to parse  SAMI configuration file" },
    { 3, "BUNDLE", 
        "Error accessing SAMI bundle info" },
    { 4, "INVTIME", 
        "Invalid time" },
    {0, 0, 0 }};

static MessFacType MessFac_SAMI = 
  { 1056, "SAMI", MessFacTab_SAMI, 0 };

#endif
