#ifndef SAMI_ERRH
#define SAMI_ERRH 1
/* C language ERROR include file
 * Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 * from input file sami_err.msg at Sun Apr 28 14:25:43 2019
 */

/* Facility number */
#define SAMI__FACNUM 1056

/* OK Status symbol */
#define SAMI__OK 0

/* File to parse  SAMI configuration file */
#define SAMI__FILE_PARSE 0xC208012

/* Error accessing SAMI bundle info */
#define SAMI__BUNDLE 0xC20801A

/* Invalid time */
#define SAMI__INVTIME 0xC208022

#endif
