#ifndef FPIL_ERRH
#define FPIL_ERRH 1
/* C language ERROR include file
 * Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 * from input file fpil_err.msg at Fri Apr 26 12:47:09 2019
 */

/* Facility number */
#define FPIL__FACNUM 1886

/* Initialisation of FPIL did not include provision of constants access routines */
#define FPIL__NOCONS 0xF5E8322

/* Initialisation of FPIL did not include provision of telescope model routines */
#define FPIL__NOMODEL 0xF5E832A

/* Failure in telescope model initialisation */
#define FPIL__MODELINITERR 0xF5E8332

/* FPIL does not provide a button drawing routine for this instrument */
#define FPIL__NODRAW 0xF5E833A

/* FPIL does not provide a Which Spectrograph routine for this instrument */
#define FPIL__NOWHICHSPEC 0xF5E8342

/* FPIL Instrument does not include a clone routine (interface not updated) */
#define FPIL__NOCLONE 0xF5E834A

#endif
