#ifndef FPIL_ERR_MSGTH
#define FPIL_ERR_MSGTH 1
/*  Message table include file
 *  Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 *  from input file fpil_err.msg at Fri Apr 26 12:29:22 2019
  */
static MessTabType MessFacTab_FPIL[] = {
    { 100, "NOCONS", 
        "Initialisation of FPIL did not include provision of constants access routines" },
    { 101, "NOMODEL", 
        "Initialisation of FPIL did not include provision of telescope model routines" },
    { 102, "MODELINITERR", 
        "Failure in telescope model initialisation" },
    { 103, "NODRAW", 
        "FPIL does not provide a button drawing routine for this instrument" },
    { 104, "NOWHICHSPEC", 
        "FPIL does not provide a Which Spectrograph routine for this instrument" },
    { 105, "NOCLONE", 
        "FPIL Instrument does not include a clone routine (interface not updated)" },
    {0, 0, 0 }};

static MessFacType MessFac_FPIL = 
  { 1886, "FPIL", MessFacTab_FPIL, 0 };

#endif
