#ifndef SIXDF_UTIL_ERR_MSGTH
#define SIXDF_UTIL_ERR_MSGTH 1
/*  Message table include file
 *  Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 *  from input file sixdf_util_err.msg at Fri Apr 26 12:34:28 2019
  */
static MessTabType MessFacTab_SIXDF_UTIL[] = {
    { 100, "MALLOCERR", 
        "Malloc error" },
    { 101, "SPRINTF", 
        "Format string exceeds available string length (ErsSPrintf)" },
    { 102, "DIRCREERR", 
        "Error creating directory" },
    { 103, "GRAPSTRLEN", 
        "Button graphics string length exceeds available space" },
    { 104, "ILLRA", 
        "Illegal RA" },
    { 105, "ILLDEC", 
        "Illegal Dec" },
    { 106, "ZDERR", 
        "ZD greater than 70 degrees" },
    { 107, "SLA_ERR_1", 
        "Slalib error, Star too far from axis" },
    { 108, "SLA_ERR_2", 
        "Slalib error, Antistar on tangent plane" },
    { 109, "SLA_ERR_3", 
        "Slalib error, Antistar too far from axis" },
    { 110, "SLA_ERR_UNKN", 
        "Unknown Slalib error" },
    {0, 0, 0 }};

static MessFacType MessFac_SIXDF_UTIL = 
  { 1876, "SIXDF_UTIL", MessFacTab_SIXDF_UTIL, 0 };

#endif
