#ifndef AATTELMDL_ERRH
#define AATTELMDL_ERRH 1
/* C language ERROR include file
 * Generated by /Users/drama/release/messgen/r3_16/macosx_x86_64/messgen utility
 * from input file aatTelMdl_Err.msg at Sun Apr 28 11:49:55 2019
 */

/* Facility number */
#define AATTELMDL__FACNUM 1055

/* OK Status symbol */
#define AATTELMDL__OK 0

/* Apparent programming error in AAT Telescope model code */
#define AATTELMDL__PROGERR 0xC1F8012

/* Invalid parameter to AAT Telescope model initialisation */
#define AATTELMDL__INVPAR 0xC1F801A

/* Slalib Ds2tp call failed */
#define AATTELMDL__SLADS2TPERR 0xC1F8022

/* Conversion failed */
#define AATTELMDL__CVTFAILED 0xC1F802A

/* Invalid observation air-mass */
#define AATTELMDL__AIRMASS 0xC1F8032

#endif
