#ifndef ARG_ERRH
#define ARG_ERRH 1
/*
 *  @(#) $Id: ACMM:sds/Standalone/arg_err.h,v 3.82 23-Dec-2015 08:24:10+11 tjf $
 */

/* C language ERROR include file
 * Generated by /instsoft/drama/release/messgen/r0_4_3/sun4_solaris/messgen utility
 * from input file arg_err.msg at Tue Apr 29 15:57:30 1997
 */

/* Facility number */
#define ARG__FACNUM 1825

/* Type Conversion Error */
#define ARG__CNVERR 0xF218322

/* Object is not a scalar */
#define ARG__NOTSCALAR 0xF21832A

/* Object is not a string */
#define ARG__NOTSTRING 0xF218332

/* Malloc failed */
#define ARG__MALLOCERR 0xF21833A

#endif
